// Cedar token build.
//
// Compiles the DTCG source under src/ into two outputs from one source of truth:
//   - dist/tokens.css   CSS custom properties: a :root block plus one
//                       [data-theme="..."] block per alternate theme.
//   - generated/index.ts  a typed `tokens` object (tsc turns this into the
//                         published dist/index.js + dist/index.d.ts).
//
// Run with: node build.js  (the package "build" script also runs tsc afterwards).

import StyleDictionary from "style-dictionary";
import { readFileSync, writeFileSync, rmSync, mkdirSync } from "node:fs";

// --- Custom transform: px -> rem -----------------------------------------
//
// Style Dictionary v5's built-in `size/rem` transform preserves an explicit
// unit ("16px" stays "16px"), so it does NOT do the px->rem conversion the
// pipeline needs. We register our own: any dimension authored in px is divided
// by a 16px root font size and emitted as rem. Zero stays unitless; any value
// not authored in px (e.g. an already-rem or unitless value) is left untouched.
const ROOT_FONT_PX = 16;

StyleDictionary.registerTransform({
  name: "cedar/size/px-to-rem",
  type: "value",
  transitive: true, // also runs on values pulled in via {references}
  filter: (token) => (token.$type ?? token.type) === "dimension",
  transform: (token, _config, options) => {
    const value = options.usesDtcg ? token.$value : token.value;
    const match = /^(-?\d*\.?\d+)px$/.exec(String(value).trim());
    if (!match) return value;
    const px = parseFloat(match[1]);
    return px === 0 ? "0" : `${px / ROOT_FONT_PX}rem`;
  },
});

// --- Custom format: typed TS object --------------------------------------
//
// Emits a nested `tokens` object mirroring the DTCG tree, with raw leaf values.
// `as const` gives tsc precise literal types when it compiles this to dist/.
StyleDictionary.registerFormat({
  name: "cedar/ts-tokens",
  format: ({ dictionary }) => {
    const toTree = (node) => {
      if (node.$value !== undefined || node.value !== undefined) {
        return node.$value ?? node.value; // leaf token
      }
      return Object.fromEntries(
        Object.entries(node).map(([k, v]) => [k, toTree(v)]),
      );
    };
    const tree = toTree(dictionary.tokens);
    return (
      "// Generated by Style Dictionary. Do not edit directly.\n" +
      `export const tokens = ${JSON.stringify(tree, null, 2)} as const;\n\n` +
      "export type Tokens = typeof tokens;\n"
    );
  },
});

// --- Shared config -------------------------------------------------------
const SRC = "src";
const TRANSFORMS = ["name/kebab", "cedar/size/px-to-rem"];
const DEFAULT_SOURCES = [
  `${SRC}/base/**/*.json`,
  `${SRC}/semantic/**/*.json`,
  `${SRC}/component/**/*.json`,
];
const THEMES = ["dark", "cedar"]; // alternate themes; default/light lives in :root

const header = (lines) => () => lines;

// --- CSS build -----------------------------------------------------------
//
// One Style Dictionary run per block. The :root run emits every token; each
// theme run loads base + that theme's overrides, then a filter keeps only the
// overriding tokens so the [data-theme] block stays small. outputReferences
// keeps values as var(--base-...) so the base<-semantic relationship survives
// into the CSS and themes re-point through it.
async function buildCssBlock(theme) {
  const isRoot = theme === null;
  // Theme blocks load only base (so {base.*} references resolve) plus their own
  // overrides — NOT the semantic defaults. Loading the defaults just to redefine
  // them is what produces Style Dictionary's "token collision" warnings.
  const source = isRoot
    ? DEFAULT_SOURCES
    : [`${SRC}/base/**/*.json`, `${SRC}/themes/${theme}/**/*.json`];
  const destination = isRoot ? ".root.css" : `.${theme}.css`;

  const sd = new StyleDictionary({
    usesDtcg: true,
    // Theme blocks intentionally reference base vars (e.g. var(--base-color-amber-600))
    // that are defined in the :root block, not in the theme block itself. Style
    // Dictionary can't see across blocks and warns about the "filtered out"
    // references; the references resolve correctly once the blocks are concatenated
    // into one stylesheet, so we silence warnings on theme builds only.
    log: isRoot ? undefined : { warnings: "disabled" },
    source,
    platforms: {
      css: {
        transforms: TRANSFORMS,
        buildPath: "dist/",
        files: [
          {
            destination,
            format: "css/variables",
            filter: isRoot
              ? undefined
              : (token) => token.filePath.includes(`themes/${theme}`),
            options: {
              outputReferences: true,
              selector: isRoot ? ":root" : `[data-theme="${theme}"]`,
              fileHeader: header(
                isRoot
                  ? [
                      "Cedar design tokens — generated by Style Dictionary.",
                      "Do not edit directly; edit the DTCG source under src/ and rebuild.",
                    ]
                  : [],
              ),
            },
          },
        ],
      },
    },
  });

  await sd.buildAllPlatforms();
  return `dist/${destination}`;
}

// --- TS build ------------------------------------------------------------
async function buildTs() {
  const sd = new StyleDictionary({
    usesDtcg: true,
    source: DEFAULT_SOURCES, // typed exports reflect the default/light theme
    platforms: {
      ts: {
        transforms: TRANSFORMS,
        buildPath: "generated/",
        files: [{ destination: "index.ts", format: "cedar/ts-tokens" }],
      },
    },
  });
  await sd.buildAllPlatforms();
}

// --- Orchestrate ---------------------------------------------------------
mkdirSync("dist", { recursive: true });
mkdirSync("generated", { recursive: true });

const rootFile = await buildCssBlock(null);
const themeFiles = [];
for (const theme of THEMES) themeFiles.push(await buildCssBlock(theme));

// Theme blocks emit an empty `/** */` header; strip it so only the :root block
// carries the generated-file banner.
const stripHeader = (css) => css.replace(/^\/\*\*[\s\S]*?\*\/\s*/, "");
const blocks = [
  readFileSync(rootFile, "utf8").trim(),
  ...themeFiles.map((file) => stripHeader(readFileSync(file, "utf8")).trim()),
];
writeFileSync("dist/tokens.css", blocks.join("\n\n") + "\n");
[rootFile, ...themeFiles].forEach((file) => rmSync(file));

await buildTs();

console.log("✓ tokens built: dist/tokens.css + generated/index.ts");
